routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('index');
    });

    Route::group(['middleware' => 'admin'], function(){
        Route::resources([
            // 'user' => 'UserController',
            'category' => 'CategoryController',
            'member_categories' => 'MemberCategoryController'
        ]);
    });

    Route::resources([
        // 'category' => 'CategoryController',
        'product' => 'ProductController',
        'promos' => 'PromoController',
        'transactions' => 'TransactionController',
        // 'member_categories' => 'MemberCategoryController',
        'members' => 'MemberController'
    ]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    protected $guarded = [];
    use SoftDeletes;

    public function productCat(){
        return $this->hasMany(Product::class, 'product_category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::all();
        $category = Category::with('productCat')->get();
        
        return view('category.index', compact('category','product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create([
            'name' => request('name'),
            'desc' => request('desc')
        ]);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $product = Product::all();
        return view('category.show', compact('category', 'product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'desc' => 'required'
        ]);

        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->desc = $request->desc;
        $category->save();

        return redirect('category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect('category');
    }
}

resources/views/category/edit.blade.php
@extends('layouts.app')
@section('title')
    Category | Edit
@endsection

@section('content')
    
    <div class="card">
        <div class="header">
            <h2>Edit Category</h2>
        </div>
        <div class="body">
            <div class="row clearfix">
                <div class="col-sm-12">
                    <form action=" {{ route('category.update', $category->id )}} " method="post" autocomplete="off">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Name" value="{{ $category->name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <textarea rows="3" name="desc" id="desc" class="form-control no-resize" placeholder="Descriptiom" >{{ $category->desc }}</textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('title')
    Category
@endsection

@section('content')
    <div class="card">
        <div class="header">
            <h2>Categories</h2>
        </div>
        <div class="body">
            <div class="card-inside-title">Form Category</div>
            <div class="row clearfix">
                <div class="col-sm-12">
                    <form action=" {{ route('category.store') }} " id="simpanData" method="post" autocomplete="off">
                        @csrf
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" name="name" id="name" placeholder="Name"  class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <textarea rows="3" name="desc" id="desc" class="form-control no-resize" placeholder="Descriptiom"></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="body">
            <div class="card-inside-title">Table Category</div>
            @include('category.table')
        </div>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')
@section('title')
    Category | Show
@endsection

@section('content')
    <div class="card">
        <div class="header">
            <h2>{{ $category->name}} <small>{{ $category->desc }}</small></h2>
        </div>
        <div class="body">
            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card-inside-title">Items</div>
                        @foreach ($category->productCat as $n => $prods)
                            <p>{{ $n+1 }}. {{ $prods->name }} </p>    
                        @endforeach
                </div>
            </div>
            <a href=" {{ route('category.index')}} "><button class="btn btn-warning">Back</button></a>
        </div>
    </div>
@endsection

resources/views/category/table.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
        <tbody>
            @foreach ($category as $n => $cats)
            <tr>
                <td>{{$n+1}}</td>
                <td>{{ $cats->name }}</td>
                <td>{{ $cats->desc }}</td>
                <td><a href=" {{ route('category.edit', $cats->id )}} ">Edit</a></td>
                <td><a href=" {{ route('category.show', $cats->id )}} ">Show</a></td>
                <td>
                    <form id="delete-data-{{ $cats->id }}" action=" {{ route('category.destroy', $cats->id) }} " method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger" onclick="deleteNih({{ $cats->id }})">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

@section('script')
<script>
        function deleteNih(id){
            event.preventDefault();
            var form = document.querySelector('#delete-data-'+id);
    
            swal({
                title: "Apa anda yakin?",
                text: "Anda tidak dapat mengembalikannya lagi!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function(){
    
                form.submit();
    
            });
    
        }

        
</script>
<script>
    
   
</script>
@endsection