routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('index');
    });

    Route::group(['middleware' => 'admin'], function(){
        Route::resources([
            // 'user' => 'UserController',
            'category' => 'CategoryController',
            'member_categories' => 'MemberCategoryController'
        ]);
    });

    Route::resources([
        // 'category' => 'CategoryController',
        'product' => 'ProductController',
        'promos' => 'PromoController',
        'transactions' => 'TransactionController',
        // 'member_categories' => 'MemberCategoryController',
        'members' => 'MemberController'
    ]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    public function products(){
        return $this->belongsTo(Category::class, 'product_category_id');
    }

    public function promo(){
        return $this->hasMany(Promo::class, 'product_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();
        $product = Product::with('products')->get();

        return view('products.index', compact('product','category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'imagessss' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            // 'image' => 'required',
            'cat_id' => 'required',
            'desc' => 'required',
            'amount' => 'required'
        ]);

        // return response()->json($request);

        if ($request->has('active')) {
            $active = 1;
         } else {
             $active = 0;
         }

        $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->imagessss->getClientOriginalExtension();

        if(!$request->imagessss->move(storage_path('app/public/produk'), $fileName)){
            return array('error' => 'Gagal upload foto');
        } else {
            $product = new Product();
            $product->name = $request->name;
            $product->image = "storage/produk/".$fileName;;
            $product->product_category_id = $request->cat_id;
            $product->desc = $request->desc;
            $product->amount = $request->amount;
            $product->save();
        }

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $category = Category::all();
        return view('products.edit', compact('product', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $productPict = Product::where("id","=",$id)->get()->first()->image;

        // return response()->json($productPict);

        if (!$request->image) {
            
            $request->validate([
                'name' => 'required',
                'cat_id' => 'required',
                'desc' => 'required',
                'amount' => 'required'
            ]);
        } else {
            $request->validate([
                'name' => 'required',
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'cat_id' => 'required',
                'desc' => 'required',
                'amount' => 'required'
            ]);

            $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->image->getClientOriginalExtension();
        }
        
        if ($request->has('active')) {
            $active = 1;
        } else {
            $active = 0;
        }
        

        $product = Product::findOrFail($id);
        $product->name = $request->name;
        $product->product_category_id = $request->cat_id;
        $product->desc = $request->desc;
        $product->amount = $request->amount;
        $product->image = $request->image;
        if($request->hasFile('image')){
            if (is_file($product->image)){
                try{
                    unlink($productPict);
                } catch(\Exception $e){

                }
            }
            $request->image->move(storage_path('app/public/produk'), $fileName);
            $product->image = "storage/produk/".$fileName;
        } else {
            $product->image = $productPict;
        }
        $product->save();

        return redirect('product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        return redirect('product');
    }
}

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('title')
    Product | Edit
@endsection

@section('content')

<div class="card">
    <div class="body">
        <div class="card-inside-title">Edit Product</div>
        <div class="row clearfix">
            <div class="col-sm-12">
                <form action=" {{ route('product.update', $product->id) }} " method="post" autocomplete="off" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <div class="form-line">
                        <input type="text" name="name" id="name" placeholder="Name"  class="form-control" value="{{ $product->name }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-line">
                            <label for="file">Upload Image</label>
                            <div class="fallback">
                                <input name="image" type="file" multiple />
                            </div>
                        </div>
                    </div>
                    {{-- <div class="form-group">
                        <div class="form-line">
                        <textarea class="form-control" name="image" id="image" rows="2" placeholder="Image">{{ $product->image }}</textarea>
                        </div>
                    </div> --}}
                    <br>
                    <div class="form-group">
                        <select class="form-control" name="cat_id" id="cat-id">
                            <option disabled selected>-- Categories --</option>
                            @foreach ($category as $item)
                                <option {{ $product->product_category_id == $item->id ? "selected" : "" }} value="{{ $item->id }}"> {{ $item->name }} </option>    
                            @endforeach
                        </select>
                        <hr>
                    </div><br>
                    <div class="form-group">
                        <div class="form-line">
                            <textarea class="form-control" name="desc" id="desc" rows="2" placeholder="Description"> {{ $product->desc }} </textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-line">
                            <input type="text" name="amount" id="amount" placeholder="Amount"  class="form-control" value=" {{ $product->amount }} ">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title')
    Product
@endsection

@section('content')
    <div class="card">
        <div class="header">
            <h2>Products</h2>
        </div>
    </div>
    <div class="card">
        <div class="body">
            <div class="card-inside-title">Form Product</div>
            <div class="row clearfix">
                <div class="col-sm-12">
                    <form action=" {{ route('product.store') }} " method="post" id="simpanData" autocomplete="off" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" name="name" id="name" placeholder="Name"  class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <label for="file">Upload Image</label>
                                <div class="fallback">
                                    <input name="imagessss" type="file" multiple />
                                </div>
                            </div>
                        </div>
                        {{-- <div class="form-group">
                            <div class="form-line">
                                <textarea class="form-control" name="image" id="image" rows="2" placeholder="Image"></textarea>
                            </div>
                        </div> --}}
                        <br>
                        <div class="form-group">
                            <select class="form-control show-tick" name="cat_id" id="cat-id">
                                <option disabled selected>-- Categories --</option>
                                @foreach ($category as $item)
                                    <option value="{{ $item->id }}"> {{ $item->name }} </option>    
                                @endforeach
                            </select>
                            <hr>
                        </div><br>
                        <div class="form-group">
                            <div class="form-line">
                                <textarea class="form-control" name="desc" id="desc" rows="2" placeholder="Description"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" name="amount" id="amount" placeholder="Price"  class="form-control">
                            </div>
                        </div>
                        <button class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="body">
            <div class="card-inside-title">Table Product</div>
            <div class="table-responsive js-sweetalert">
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                    <thead>
                        <tr>
                            <td>No</td>
                            <td>Name</td>
                            <td>Image</td>
                            <td>Category</td>
                            <td>Description</td>
                            <td>Price</td>
                            <td>Edit</td>
                            <td>Hapus</td>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td>No</td>
                            <td>Name</td>
                            <td>Image</td>
                            <td>Category</td>
                            <td>Description</td>
                            <td>Price</td>
                            <td>Edit</td>
                            <td>Hapus</td>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($product as $n => $prods)
                            <tr>
                                <td>{{ $n+1 }}</td>
                                <td>{{ $prods->name }}</td>
                                <td><img src="{{ $prods->image }}" height="80px" width="auto" alt="gambar" class="ssimg-thumbnail"></td>
                                <td>{{ $prods->products['name'] }}</td>
                                <td>{{ $prods->desc }}</td>
                                <td>{{ $prods->amount }}</td>
                                <td>
                                    <a href="{{ route('product.edit', $prods->id) }}">
                                        <button class="btn btn-success">Edit</button>
                                    </a>
                                </td>
                                <td>
                                    <form id="delete-data-{{ $prods->id }}" action=" {{ route('product.destroy', $prods->id) }} " method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger waves-effect" onclick="deleteNih({{ $prods->id }})">Delete</button>
                                    </form>
                                    
                                </td>
                            </tr>
                        @endforeach
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection